sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - composer test

notifications:
  email: false
